# Generated by Django 5.1.7 on 2025-03-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='contrasena',
        ),
        migrations.AddField(
            model_name='alumno',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
