# Generated by Django 5.1.7 on 2025-03-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_remove_alumno_contrasena_alumno_google_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='contrasena',
            field=models.CharField(default='password123', max_length=255),
            preserve_default=False,
        ),
    ]
