# Generated by Django 5.1.7 on 2025-03-22 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumno_contrasena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='google_id',
        ),
    ]
